name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Update apt
      run: sudo apt-get update --fix-missing
    
    - name: Install tree
      run: sudo apt-get install tree

    - name: Install norminette
      run: pip install norminette

    - name: Run tree
      run: tree

    - name: Run norminette
      run: norminette src include

    - name: Make get_next_line as a module
      run: make module

    - name: View contents of obj
      run: ls -la obj/

    - name: Clean output
      run: make clean

    - name: Make get_next_line as standalone
      run: make all

    - name: Re-make get_next_line
      run: make re

    - name: View contents of standalone
      run: nm -C build/libftgnl.a

