name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make program as module
      run: make module

    - name: View Contents of bin
      run: ls -la obj/

    - name: Clean output
      run: make clean

    - name: Make program as standalone
      run: make all

    - name: Re-make program
      run: make re

    - name: View Contents of standalone
      run: nm build/libgnl.a

