name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make program
      run: make

    - name: Re-make program
      run: make re

    - name: View Contents of bin
      run: ls -la obj/
